# Generated by Django 5.2.1 on 2025-08-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Eg: John Doe', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone_number', models.CharField(default='0000000000', max_length=20)),
                ('service_type', models.CharField(choices=[('installation', 'AC Installation'), ('repairs', 'Repairs & Troubleshooting'), ('maintenance', 'Maintenance'), ('energy', 'Energy Efficiency Solutions')], default='installation', max_length=50)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('date_of_booking', models.DateTimeField(auto_now_add=True)),
                ('preferred_date', models.DateField(default='2025-12-31')),
            ],
            options={
                'verbose_name': 'Service Requests',
                'ordering': ['-date_of_booking'],
            },
        ),
        migrations.CreateModel(
            name='TrainingApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Eg: John Doe', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('phone_number', models.CharField(default='0000000000', max_length=20)),
                ('program', models.CharField(choices=[('apprenticeship', 'Apprenticeship'), ('short-course', 'Short Course'), ('professional', 'Professional Certification')], default='apprenticeship', max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'verbose_name': 'Application Requests',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
